# Generated by Django 3.0.2 on 2020-01-04 12:20

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/default.jpg', upload_to='images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('news_data', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
            ],
        ),
    ]
